blank_issues_enabled: false
contact_links:
  - name: 💖 Sponsor PegaProx
    url: https://pegaprox.com/#sponsor
    about: Help us dedicate more time to PegaProx by becoming a sponsor!
  - name: 📖 Documentation
    url: https://docs.pegaprox.com
    about: Check the docs first — your answer might already be there.
